### ISSUE TITLE
LexerCore ignores double quotes in SIP Header Parameter values

### ISSUE THREAD

**Issue by stefanLeo** [Mobicents/jain-sip#23]
We are using JainSip Stack as the foundation of our SIP Software and during integration with a 3rd party SIP Server we recognized an issue inside the LexerCore, which is not supporting double quotes in header param values.
 
Our example is a subscription-state header, but this accounts for any SIP header.
Exemplary Unit Test that fails:
```java
@Test
public void testCreateHeaderWithDoubleQuotes() throws Exception {
        HeaderFactoryImpl factory = new HeaderFactoryImpl();
        Header customStateHeader = factory.createHeader("Subscription-State: terminated;reason=SIP ;text=\"Call Expired\"");
        assertNotNull(customStateHeader);
        assertTrue("White spaces and double quotes haven't been removed", customStateHeader.toString().contains("Subscription-State: terminated;reason=SIP;text=CallExpired"));
    }
```

We also looked up in the RFCs (https://www.ietf.org/rfc/rfc3261.txt) if the double quotes are supported and found that in 25.1 Page 221 there is a definition of a quoted-string:
    quoted-string  =  SWS DQUOTE *(qdtext / quoted-pair ) DQUOTE
So it seems that this is standard conform.

Issue is more or less caused by the LexerCore match(ID) method. 
It is expecting that the lexer is currently placed on a supported token, but is placed on the first double quote. This results in a ParseException ignoring this header completely. 

Expected would be that the lexer takes the value (including whitespaces) inside of the double quotes as parameter value.

We would really appreciate your help. Thank you.

**Comment by deruelle** [comment]
Thanks @stefanLeo for opening this issue. @jaimecasero will look into it.
Which company are you from and which software will use the JAIN SIP Stack ?

**Comment by jaimecasero** [comment]
Hi Stefan,
Thanks for the so well documented issue.

Actual problem comes from SubscriptionStateParser class, where "gen-value      =  token / host / quoted-string" as defined in RFC is not completely supported. Basically it is assumed a token will be there.

I can't help noticing  your test asserts using toString().contains("Subscription-State: terminated;reason=SIP;text=CallExpired"). I don't know about this "text" param, but if it's an option for you, you may try using "text=CallExpired" instead of "text=\"Call Expired\"". In that case it will work as expected. Notice that if the value has an space in between, then there will be problems. Since I don't know where is the valid value (initial injection, or assertion) I was suggesting this as a workaround.

Please let me know your thoughts about it.

Regards.

**Comment by stefanLeo** [comment]
Hi 

Thx for the quick replies!
I already applied this trick as a workaround (stripping the double quotes and any whitespaces within before passing the header on to SubscriptionStateParser).
Therefore I registered my own version of StringMsgParser, which works pretty well.

Unfortunately we are not producing this subscription message on our own and I can not influence the messages sent by the remote party (in this a case a 3rd party integration). I was also surprised by the text param :-) Unfortunately we need to verify against this param value somehow.  

FYI: My company is Frequentis AG Austria
We are currently using it for an in-house integration testing software where we have to integrate with several SIP / RTP interfaces.

Thx for your support.

**Comment by jaimecasero** [comment]
I was afraid about having a third party involved. Let me have a look on how much effort we would need to fully support generic-params, since this will enable unexpected scenarios for everybody.

**Comment by stefanLeo** [comment]
That'd be great. Thx!

**Comment by jaimecasero** [comment]
Stefan,
Looking at different parsers the quotedString parsing is supported. If you take a look at SubscriptionStateParser, this small patch did the trick:
 else {
                    this.lexer.match('=');
                    this.lexer.SPorHT();
                    try {
                        lexer.match(TokenTypes.ID);
                        Token secondToken = lexer.getNextToken();
                        String secondValue = secondToken.getTokenValue();
                        subscriptionState.setParameter(value, secondValue);
                    } catch (ParseException pExp) {
                        String paramValue = this.lexer.quotedString();
                        subscriptionState.setParameter(value, paramValue);
                    }
                }

As you can see, the Token is attempted then the quotedString. I need to introduce more unit tests for this, and probably make sure this performs appropiately. But I'm looking forward to release a patch this week.
