### ISSUE TITLE
Javascript Port of JAIN-SIP-Stack

### ISSUE THREAD

**Issue by benjaminbohlmann** [Mobicents/jain-sip#36]
Hi,

this is not a real issue, but more a question where I don't know where to post it:
When this project was still hosted on google code, there was a javascript port of the jain-sip stack. Do you know where it went, after the project was migrated over to github?

Thanks for your help and sorry if this is the wrong spot to ask this.
Ben

**Comment by deruelle** [comment]
It is located here https://github.com/Mobicents/webrtcomm/tree/master/jain-sip-js
