### ISSUE TITLE
BYE sent to wrong address

### ISSUE THREAD

**Issue by hrosa** [Mobicents/jain-sip#42]
I'm currently running performance tests against RestComm + XMS solution, both deployed in separate servers. The JSR 309 driver of Dialogic relies on SIP Servlets to communicate with XMS.

This particular version of RestComm is using latest MSS version at the moment (3.1.646).

When using SIPp, I discovered that sometimes timeouts would occur when SIPp was expecting BYE from RestComm. Even when the number of concurrent calls is low (10-15CPS).

<img width="1552" alt="screen shot 2015-12-16 at 12 17 49" src="https://cloud.githubusercontent.com/assets/7796608/11869913/2f3d3f08-a4bb-11e5-9fd4-384022132d56.png">

Looking at [RestComm log](https://drive.google.com/file/d/0B5JaYasUXc04a1BTbFhaSmhmV3c/view?usp=sharing), I discovered the reason behind the timeouts: somehow, RestComm was sending BYE to the Media Server instead of SIPp:
```
Will sent out BYE to: sip:<xms_address>:5060
```
I am also attaching a [wireshark trace](https://drive.google.com/a/telestax.com/file/d/0B5JaYasUXc04U1BZRnA2anliVkE/view?usp=sharing) with 4 failed calls in 45. To check for failed calls, go to "Voip Calls" in Wireshark Menu and select the ones with greater "Stop Time".

It seems that this problem only happens when transport is UDP.
The timeout issue was gone once I repeated the tests with SIPp using TCP.

<img width="566" alt="screen shot 2015-12-17 at 12 51 41" src="https://cloud.githubusercontent.com/assets/7796608/11870149/f8c92fc0-a4bc-11e5-8330-7a7414fc8fbb.png">

**Comment by jaimecasero** [comment]
ok let me decode that for you

restcomm instance (EC2): private=10.81.151.249, public=50.16.116.247


Dialogic XMS: 50.84.100.82

SIPp is running on RestComm instance


so yes,


the problem is when the BYE is sent to


50.84.100.82

**Comment by jaimecasero** [comment]
It's worth noting that on failing calls, there are two BYEs sent. First one as commented goes to Media Server, but second ones goes to sipp (BYE sip:+1234@50.16.116.247:5080 SIP/2.0), but tx/callid is not found.

**Comment by jaimecasero** [comment]
https://github.com/Mobicents/RestComm/blob/1172976ec62ee83ccd3a8fd58d7db97e9f0f78fc/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/Call.java#L1375

https://github.com/Mobicents/RestComm/blob/1172976ec62ee83ccd3a8fd58d7db97e9f0f78fc/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/Call.java#L315


https://github.com/Mobicents/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L2348

It seems failing call has a realInetURI different form null. The working calls populated that att to null, so the bye is not changed.

This trace shows the moment when bye uri is changed to the realInetUri


14:14:30,196 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-54) Using the real ip address of the sip client sip:54.84.100.82:5060 as a request uri of the BYE request


this change is enabled with this code 

if (realInetUri != null && (byeRURI.isSiteLocalAddress() || byeRURI.isAnyLocalAddress() || byeRURI.isLoopbackAddress())) {
               logger.info("Using the real ip address of the sip client " + realInetUri.toString()
               + " as a request uri of the BYE request");
               bye.setRequestURI(realInetUri);
           }

**Comment by jaimecasero** [comment]
Suggested a workaround for UDP scenairo, is to locate SIPp in a different box than Restcomm, so hopefully conditions are not enable, and bye uri is not changed

**Comment by jaimecasero** [comment]
This myabe related:
14:14:25,490 DEBUG [org.mobicents.servlet.sip.message.SipServletMessageImpl] (RestComm-akka.actor.default-dispatcher-62) transaction gov.nist.javax.sip.stack.SIPServerTransactionImpl@407b7ad2 transactionId = null transactionType false
14:14:25,492 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-62) Contact header address <sip:sipp@10.81.151.249:54858> is a private network ip address, storing Initial Remote Address 54.84.100.82:5060 to the session for later use

Saving for the record

**Comment by jaimecasero** [comment]
else if (contactInetAddress.isSiteLocalAddress() && !recordRouteHeaders.hasNext()
                && !contactInetAddress.toString().equalsIgnoreCase(inetAddress.toString())) {
            logger.info("Contact header address " + contactAddr.toString()
                    + " is a private network ip address, storing Initial Remote Address " + realIP + ":" + realPort
                    + " to the session for later use");
            realIP = realIP + ":" + realPort;
            uri = factory.createSipURI(null, realIP);
        }

So, the realIP is updated when Contact header  and msg.initialRemoteAddr are diff. Please notice there is a potential DNS lookup in place InetAddress.getByName

**Comment by hrosa** [comment]
Find logs and tcpdump attached [here](https://drive.google.com/a/telestax.com/file/d/0B5JaYasUXc04OGFwbzdCamJKcjg/view?usp=sharing)

**Comment by deruelle** [comment]
which packet or CallID is in error ? I can't see the trace for "Using the real ip address of the sip client" anymore when greping the new log file.

**Comment by jaimecasero** [comment]
Agreed with Jean to change SIPServletRequestImpl methods to take message inf before tx.
