### ISSUE TITLE
Threads created by ScheduledExecutorSipTimer and MultiPipelineExecutor should have human readable names

### ISSUE THREAD

**Issue by AlerantAppNGIN** [Mobicents/jain-sip#7]
It would be nice in

- gov.nist.javax.sip.stack.timers.ScheduledExecutorSipTimer and

- gov.nist.javax.sip.stack.MultiPipelineExecutor classes

to use a ThreadFactory extension which names created threads in a human readable way (for example "pool-<basename>-thread-n").

As a result of this improvement it would be easier to debug/analyze thread/memory dumps and logs in sip servers using jain-sip.

**Comment by deruelle** [comment]
Can you make a pull request of this ?

**Comment by AlerantAppNGIN** [comment]
I believe, I did it already:

https://github.com/Mobicents/jain-sip/pull/8

**Comment by deruelle** [comment]
Merged
